import React from 'react'

export default function TermsAndCondition() {
    return (
        <div className="terms-and-condition-wrapper">
            <h2>Cheeky-Chic Terms and Conditions</h2>
            <h6>Last updated April 1, 2020</h6>
            <div className="terms-and-condition">
                <h4>AGREEMENT TO TERMS</h4>    

                <p> These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on 
                    behalf of an entity you and we, concerning your access to and use of the cheeky-chic website as well as any other media form, 
                    media channel, mobile website or mobile application related, linked, or otherwise connected thereto collectively.
                </p>
                <p>
                    You agree that by accessing the Site, you have read, understood, and agree to be bound by all of these Terms and Conditions. 
                    If you do not agree with all of these Terms and Conditions, then you are expressly prohibited from using the Site and you must 
                    discontinue use immediately.
                </p>

                <p>Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated 
                    herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms and Conditions 
                    at any time and for any reason.
                </p> 
                
                <p>We will alert you about any changes by updating the “Last updated” date of these Terms and 
                    Conditions, and you waive any right to receive specific notice of each such change. 
                </p>

                <p>It is your responsibility to periodically review these Terms and Conditions to stay informed of updates. 
                    You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms and Conditions by your continued use of the Site after the date such 
                    revised Terms and Conditions are posted.
                </p>

                <p>The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or 
                    country where such distribution or use would be contrary to law or regulation or which would subject us to any registration 
                    requirement within such jurisdiction or country.
                </p>

                <p>Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely 
                    responsible for compliance with local laws, if and to the extent local laws are applicable.
                </p>

                <p>These terms and conditions were generated by Termly’s Terms and Conditions Generator.</p>    

                <p><b>Option 1:</b> The Site is intended for users who are at least 18 years old. Persons under the age of 18 are not permitted 
                    to register for the Site.
                </p>

                <p><b>Option 2:</b> [The Site is intended for users who are at least 13 years of age.] All users who are minors in the jurisdiction 
                    in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or 
                    guardian to use the Site. If you are a minor, you must have your parent or guardian read and agree to these Terms and Conditions 
                    prior to you using the Site.
                </p>   

                <h4>INTELLECTUAL PROPERTY RIGHTS</h4> 
                <p> Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website 
                    gns, audio, video, text, photographs, and graphics on the Site collectively and the trademarks, service marks, and 
                    logos contained therein the “Marks” are owned or controlled by us or licensed to us, and are protected by copyright and trademark 
                    laws and various other intellectual property rights and unfair competition laws of the United States, foreign jurisdictions, and 
                    international conventions.
                </p>

                <p>The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. 
                    Except as expressly provided in these Terms and Conditions, no part of the Site and no Content or Marks may be copied, 
                    reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, 
                    sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.
                </p>

                <p> Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or 
                    print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. 
                    We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.
                </p>

                <h4>USER REPRESENTATIONS</h4>   

                <p>By using the Site, you represent and warrant that: 
                    (1) all registration information you submit will be true, accurate, current, and complete; <br />
                    (2) you will maintain the accuracy of such information and promptly update such registration information as necessary;] <br />
                    (3) you have the legal capacity and you agree to comply with these Terms and Conditions; <br />
                    (4) you are not under the age of 13; <br />
                    (5) not a minor in the jurisdiction in which you reside [, or if a minor, you have received parental permission to use the Site];<br />
                    (6) you will not access the Site through automated or non-human means, whether through a bot, script, or otherwise; <br />
                    (7) you will not use the Site for any illegal or unauthorized purpose; <br />
                    (8) your use of the Site will not violate any applicable law or regulation. <br />
                </p>

                <p>If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or 
                    terminate your account and refuse any and all current or future use of the Site (or any portion thereof).
                </p>

                <h4>USER REGISTRATION</h4>

                <p>You may be required to register with the Site. You agree to keep your password confidential and will be responsible for all use of 
                    your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole 
                    discretion, that such username is inappropriate, obscene, or otherwise objectionable.
                </p>
                    
                <h4>PROHIBITED ACTIVITIES</h4>

                <p>You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used 
                    in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
                </p>
                
                <p>As a user of the Site, you agree not to:</p>

                <p> 1. systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, 
                    compilation, database, or directory without written permission from us. <br />
                    2. make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or 
                    other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.<br />
                    3. use a buying agent or purchasing agent to make purchases on the Site.<br />
                    4. use the Site to advertise or offer to sell goods and services. <br />
                    5. circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or 
                    restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein. <br />
                    6. engage in unauthorized framing of or linking to the Site. <br />
                    7. trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as 
                    user passwords; <br />
                    8. make improper use of our support services or submit false reports of abuse or misconduct. <br />
                    9. engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, 
                    robots, or similar data gathering and extraction tools. <br />
                    10. interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site. <br />
                    11. attempt to impersonate another user or person or use the username of another user. <br />
                    sell or otherwise transfer your profile.
                    12. use any information obtained from the Site in order to harass, abuse, or harm another person. <br />
                    13. use the Site as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or 
                    commercial enterprise. <br />
                    14. decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site. <br />
                    15. attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site. <br />
                    16. harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site to you. <br />
                    17. delete the copyright or other proprietary rights notice from any Content. <br />
                    18. copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code. <br />
                    19. upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of 
                    capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the 
                    Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Site. <br />
                    20. upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or 
                    transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other 
                    similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”). <br />
                    21. except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated 
                    system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or 
                    launching any unauthorized script or other software. <br />
                    22. disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site. <br />
                    23. use the Site in a manner inconsistent with any applicable laws or regulations. <br />
                </p>

                <h4>USER GENERATED CONTRIBUTIONS</h4>

                <p>The Site may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality, 
                    and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and 
                    materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or 
                    personal information or other material (collectively, “Contributions”).
                </p>

                <p>Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated 
                    as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:
                </p>

                <p>
                    1. the creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions 
                    do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral 
                    rights of any third party. <br/>
                    2. you are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, 
                    the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms and Conditions. <br/>
                    3. you have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name 
                    or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by 
                    the Site and these Terms and Conditions. <br/>
                    4. your Contributions are not false, inaccurate, or misleading. <br/>
                    5. your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, 
                    or other forms of solicitation. <br/>
                    6. your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable 
                    (as determined by us). <br/>
                    7. your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone. <br/>
                    8. your Contributions do not advocate the violent overthrow of any government or incite, encourage, or threaten physical harm against another. <br/>
                    9. your Contributions do not violate any applicable law, regulation, or rule. <br/>
                    10. your Contributions do not violate the privacy or publicity rights of any third party. <br/>
                    11. your Contributions do not contain any material that solicits personal information from anyone under the age of 18 or exploits people under the 
                    age of 18 in a sexual or violent manner.  <br/>
                    12. your Contributions do not violate any federal or state law concerning child pornography, or otherwise intended to protect the health or well-being 
                    of minors; <br/>
                    13. your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical 
                    handicap. <br/>
                    14. your Contributions do not otherwise violate, or link to material that violates, any provision of these Terms and Conditions, or any applicable 
                    law or regulation. <br/>
                    15. Any use of the Site in violation of the foregoing violates these Terms and Conditions and may result in, among other things, termination or 
                    suspension of your rights to use the Site. <br/>
                </p>

                <h4>CONTRIBUTION LICENSE</h4>   

                <p>By posting your Contributions to any part of the Site [or making Contributions accessible to the Site by linking your account from the Site to any 
                    of your social networking accounts], you automatically grant, and you represent and warrant that you have the right to grant, to us an unrestricted, 
                    unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right, and license to host, use, copy, reproduce, 
                    disclose, sell, resell, publish, broadcast, retitle, archive, store, cache, publicly perform, publicly display, reformat, translate, transmit, excerpt 
                    (in whole or in part), and distribute such Contributions (including, without limitation, your image and voice) for any purpose, commercial, advertising, 
                    or otherwise, and to prepare derivative works of, or incorporate into other works, such Contributions, and grant and authorize sublicenses of the foregoing. 
                    The use and distribution may occur in any media formats and through any media channels.
                </p> 

                <p>This license will apply to any form, media, or technology now known or hereafter developed, and includes our use of your name, company name, and franchise 
                    name, as applicable, and any of the trademarks, service marks, trade names, logos, and personal and commercial images you provide. You waive all moral 
                    rights in your Contributions, and you warrant that moral rights have not otherwise been asserted in your Contributions. <br/><br/>
            
                    We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or 
                    other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided 
                    by you in any area on the Site. <br/><br/>

                    You are solely responsible for your Contributions to the Site and you expressly agree to exonerate us from any and all responsibility and to refrain 
                    from any legal action against us regarding your Contributions. <br/><br/>

                    We have the right, in our sole and absolute discretion, (1) to edit, redact, or otherwise change any Contributions; (2) to re-categorize any Contributions 
                    to place them in more appropriate locations on the Site; and (3) to pre-screen or delete any Contributions at any time and for any reason, without notice. 
                    We have no obligation to monitor your Contributions.
                </p>

                <h4>GUIDELINES FOR REVIEWS</h4>
                <p>We may provide you areas on the Site to leave reviews or ratings. When posting a review, you must comply with the following criteria: <br/><br/>

                    (1) you should have firsthand experience with the person/entity being reviewed;<br/>
                    (2) your reviews should not contain offensive profanity, or abusive, racist, offensive, or hate language;<br/>
                    (3) your reviews should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, 
                    sexual orientation, or disability;<br/>
                    (4) your reviews should not contain references to illegal activity; <br/>
                    (5) you should not be affiliated with competitors if posting negative reviews; <br/>
                    (6) you should not make any conclusions as to the legality of conduct; <br/>
                    (7) you may not post any false or misleading statements; <br/>
                    (8) you may not organize a campaign encouraging others to post reviews, whether positive or negative. <br/><br/>

                    We may accept, reject, or remove reviews in our sole discretion. We have absolutely no obligation to screen reviews or to delete reviews, 
                    even if anyone considers reviews objectionable or inaccurate. Reviews are not endorsed by us, and do not necessarily represent our opinions 
                    or the views of any of our affiliates or partners. <br/><br/>

                    We do not assume liability for any review or for any claims, liabilities, or losses resulting from any review. By posting a review, you hereby 
                    grant to us a perpetual, non-exclusive, worldwide, royalty-free, fully-paid, assignable, and sublicensable right and license to reproduce, modify, 
                    translate, transmit by any means, display, perform, and/or distribute all content relating to reviews. 
                </p>

                <h4>MOBILE APPLICATION LICENSE</h4>

                <p>Use License <br/><br/>

                    If you access the Site via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and 
                    use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices 
                    strictly in accordance with the terms and conditions of this mobile application license contained in these Terms and Conditions. <br/><br/>

                    You shall not: <br/><br/>

                    (1) decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the application;<br/>
                    (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the application;<br/>
                    (3) violate any applicable laws, rules, or regulations in connection with your access or use of the application;<br/>
                    (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the application;<br/>
                    (5) use the application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended;<br/>
                    (6) make the application available over a network or other environment permitting access or use by multiple devices or users at the same time; <br/>
                    (7) use the application for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute 
                    for the application; <br/>
                    (8) use the application to send automated queries to any website or to send any unsolicited commercial e-mail; <br/>
                    (9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, 
                    licensing, or distribution of any applications, accessories, or devices for use with the application. <br/>
                </p>

                <h4>PRIVACY POLICY</h4>    

                <p>We care about data privacy and security. Please review our Privacy Policy posted on the Site. By using the Site, you agree to be bound by our Privacy 
                    Policy, which is incorporated into these Terms and Conditions. Please be advised the Site is hosted in the United States. <br/><br/>
                    If you access the Site from the European Union, Asia, or any other region of the world with laws or other requirements governing personal 
                    data collection, use, or disclosure that differ from applicable laws in the United States, then through your continued use of the Site, 
                    you are transferring your data to the United States, and you expressly consent to have your data transferred to and processed in the United States. <br/><br/>
                </p>

                <h4>DISCLAIMER</h4>    

                <p>THE SITE IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SITE AND OUR SERVICES WILL BE AT YOUR SOLE RISK. 
                    TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SITE AND YOUR USE THEREOF, 
                    INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO 
                    WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SITE AND WE 
                    WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY 
                    DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS 
                    AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM 
                    THE SITE, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (6) ANY 
                    ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, 
                    TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE 
                    ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SITE, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR 
                    OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS 
                    OF PRODUCTS OR SERVICES. <br/><br/>

                    AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE 
                    APPROPRIATE. <br/><br/>
                </p>
                            
                <h4>CONTACT US</h4>

                <p>In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at: </p>

                <h5>Cheeky-Chic<br/>
                    123 Street, Warsaw, Poland<br/>
                    012-234-567<br/>
                    cheekychic@gmail.com<br/>
                </h5>
            </div>
        </div>
    )
}
